services:
  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
      - db

  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
      - db

  user-service:
    build: ./user-service
    ports:
      - "8084:8084"
    depends_on:
      - service-registry
      - db

  db:
    image: 'postgres:17'
    container_name: mercheazy_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mercheazy-db
