services:
  db:
    image: 'postgres:17'
    container_name: mercheazy_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mercheazy-db
