spring:
  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true
      config:
        enabled: true

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
