name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - service-registry
          - api-gateway
          - auth-service
          - user-service
          - store-service
          - product-service
          - order-service
          - cart-service
          - cloudinary-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/${{ matrix.service }}
          file: ./backend/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mercheazy-${{ matrix.service }}

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mercheazy-frontend
